### ISSUE TITLE
Aspect ratio is not applied correctly

### ISSUE THREAD

**Issue by martinmueller4voice** [madskristensen/SvgViewer#10]
**Describe the bug**
The image is always 250x250 px and does not consider the aspect ratio of the SVG document.

Since the repo seems to block pushing for new branches, here is the fixed version of SvgAdornment.cs
[SvgAdornment.zip](https://github.com/madskristensen/SvgViewer/files/10173955/SvgAdornment.zip)

**Comment by madskristensen** [comment]
Thanks so much. I've updated the extension with your code and am publishing a new version right now.

**Comment by martinmueller4voice** [comment]
Great!
Thanks for creating this extension in the first place.
Cheers
Martin

Von meinem Eifon gesendet

Am 07.12.2022 um 18:30 schrieb Mads Kristensen ***@***.***>:

﻿

Thanks so much. I've updated the extension with your code and am publishing a new version right now.
