### ISSUE TITLE
Doesn't work in Visual Studio 2022

### ISSUE THREAD

**Issue by SmartK8** [madskristensen/SvgViewer#8]
Simple as that. I've tried many SVG. No joy.

regards,
Kate

**Comment by DarthSonic** [comment]
Same for me.

**Comment by SmartK8** [comment]
As a workaround I switched my default viewer on SVG (open with) to XML Editor. It worked, but I also build my own version of extension, but it might work in vanilla extension.

**Comment by hatakealex** [comment]
> As a workaround I switched my default viewer on SVG (open with) to XML Editor. It worked, but I also build my own version of extension, but it might work in vanilla extension.

fix works, but it's not convenient

**Comment by Orgbrat** [comment]
The above workaround from @SmartK8 that was recommended, using the XML Editor does display the SVG image. But nothing else seems to work.
